// var myDeserializedClass = JsonSerializer.Deserialize<GHA>(myJsonResponse);
#pragma warning disable

using System.Text.Json.Serialization;

namespace ShareX.CommonUI.Types;

public record Actor(
        [property: JsonPropertyName("login")] string Login,
        [property: JsonPropertyName("id")] int? Id,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("avatar_url")] string AvatarUrl,
        [property: JsonPropertyName("gravatar_id")] string GravatarId,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("followers_url")] string FollowersUrl,
        [property: JsonPropertyName("following_url")] string FollowingUrl,
        [property: JsonPropertyName("gists_url")] string GistsUrl,
        [property: JsonPropertyName("starred_url")] string StarredUrl,
        [property: JsonPropertyName("subscriptions_url")] string SubscriptionsUrl,
        [property: JsonPropertyName("organizations_url")] string OrganizationsUrl,
        [property: JsonPropertyName("repos_url")] string ReposUrl,
        [property: JsonPropertyName("events_url")] string EventsUrl,
        [property: JsonPropertyName("received_events_url")] string ReceivedEventsUrl,
        [property: JsonPropertyName("type")] string Type,
        [property: JsonPropertyName("user_view_type")] string UserViewType,
        [property: JsonPropertyName("site_admin")] bool? SiteAdmin
    );

    public record HeadCommit(
        [property: JsonPropertyName("id")] string Id,
        [property: JsonPropertyName("tree_id")] string TreeId,
        [property: JsonPropertyName("message")] string Message,
        [property: JsonPropertyName("timestamp")] DateTime? Timestamp,
        [property: JsonPropertyName("author")] Author Author,
        [property: JsonPropertyName("committer")] Committer Committer
    );

    public record HeadRepository(
        [property: JsonPropertyName("id")] int? Id,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("full_name")] string FullName,
        [property: JsonPropertyName("private")] bool? Private,
        [property: JsonPropertyName("owner")] Owner Owner,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("description")] string Description,
        [property: JsonPropertyName("fork")] bool? Fork,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("forks_url")] string ForksUrl,
        [property: JsonPropertyName("keys_url")] string KeysUrl,
        [property: JsonPropertyName("collaborators_url")] string CollaboratorsUrl,
        [property: JsonPropertyName("teams_url")] string TeamsUrl,
        [property: JsonPropertyName("hooks_url")] string HooksUrl,
        [property: JsonPropertyName("issue_events_url")] string IssueEventsUrl,
        [property: JsonPropertyName("events_url")] string EventsUrl,
        [property: JsonPropertyName("assignees_url")] string AssigneesUrl,
        [property: JsonPropertyName("branches_url")] string BranchesUrl,
        [property: JsonPropertyName("tags_url")] string TagsUrl,
        [property: JsonPropertyName("blobs_url")] string BlobsUrl,
        [property: JsonPropertyName("git_tags_url")] string GitTagsUrl,
        [property: JsonPropertyName("git_refs_url")] string GitRefsUrl,
        [property: JsonPropertyName("trees_url")] string TreesUrl,
        [property: JsonPropertyName("statuses_url")] string StatusesUrl,
        [property: JsonPropertyName("languages_url")] string LanguagesUrl,
        [property: JsonPropertyName("stargazers_url")] string StargazersUrl,
        [property: JsonPropertyName("contributors_url")] string ContributorsUrl,
        [property: JsonPropertyName("subscribers_url")] string SubscribersUrl,
        [property: JsonPropertyName("subscription_url")] string SubscriptionUrl,
        [property: JsonPropertyName("commits_url")] string CommitsUrl,
        [property: JsonPropertyName("git_commits_url")] string GitCommitsUrl,
        [property: JsonPropertyName("comments_url")] string CommentsUrl,
        [property: JsonPropertyName("issue_comment_url")] string IssueCommentUrl,
        [property: JsonPropertyName("contents_url")] string ContentsUrl,
        [property: JsonPropertyName("compare_url")] string CompareUrl,
        [property: JsonPropertyName("merges_url")] string MergesUrl,
        [property: JsonPropertyName("archive_url")] string ArchiveUrl,
        [property: JsonPropertyName("downloads_url")] string DownloadsUrl,
        [property: JsonPropertyName("issues_url")] string IssuesUrl,
        [property: JsonPropertyName("pulls_url")] string PullsUrl,
        [property: JsonPropertyName("milestones_url")] string MilestonesUrl,
        [property: JsonPropertyName("notifications_url")] string NotificationsUrl,
        [property: JsonPropertyName("labels_url")] string LabelsUrl,
        [property: JsonPropertyName("releases_url")] string ReleasesUrl,
        [property: JsonPropertyName("deployments_url")] string DeploymentsUrl
    );

    public record Owner(
        [property: JsonPropertyName("login")] string Login,
        [property: JsonPropertyName("id")] int? Id,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("avatar_url")] string AvatarUrl,
        [property: JsonPropertyName("gravatar_id")] string GravatarId,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("followers_url")] string FollowersUrl,
        [property: JsonPropertyName("following_url")] string FollowingUrl,
        [property: JsonPropertyName("gists_url")] string GistsUrl,
        [property: JsonPropertyName("starred_url")] string StarredUrl,
        [property: JsonPropertyName("subscriptions_url")] string SubscriptionsUrl,
        [property: JsonPropertyName("organizations_url")] string OrganizationsUrl,
        [property: JsonPropertyName("repos_url")] string ReposUrl,
        [property: JsonPropertyName("events_url")] string EventsUrl,
        [property: JsonPropertyName("received_events_url")] string ReceivedEventsUrl,
        [property: JsonPropertyName("type")] string Type,
        [property: JsonPropertyName("user_view_type")] string UserViewType,
        [property: JsonPropertyName("site_admin")] bool? SiteAdmin
    );

    public record Repository(
        [property: JsonPropertyName("id")] int? Id,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("full_name")] string FullName,
        [property: JsonPropertyName("private")] bool? Private,
        [property: JsonPropertyName("owner")] Owner Owner,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("description")] string Description,
        [property: JsonPropertyName("fork")] bool? Fork,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("forks_url")] string ForksUrl,
        [property: JsonPropertyName("keys_url")] string KeysUrl,
        [property: JsonPropertyName("collaborators_url")] string CollaboratorsUrl,
        [property: JsonPropertyName("teams_url")] string TeamsUrl,
        [property: JsonPropertyName("hooks_url")] string HooksUrl,
        [property: JsonPropertyName("issue_events_url")] string IssueEventsUrl,
        [property: JsonPropertyName("events_url")] string EventsUrl,
        [property: JsonPropertyName("assignees_url")] string AssigneesUrl,
        [property: JsonPropertyName("branches_url")] string BranchesUrl,
        [property: JsonPropertyName("tags_url")] string TagsUrl,
        [property: JsonPropertyName("blobs_url")] string BlobsUrl,
        [property: JsonPropertyName("git_tags_url")] string GitTagsUrl,
        [property: JsonPropertyName("git_refs_url")] string GitRefsUrl,
        [property: JsonPropertyName("trees_url")] string TreesUrl,
        [property: JsonPropertyName("statuses_url")] string StatusesUrl,
        [property: JsonPropertyName("languages_url")] string LanguagesUrl,
        [property: JsonPropertyName("stargazers_url")] string StargazersUrl,
        [property: JsonPropertyName("contributors_url")] string ContributorsUrl,
        [property: JsonPropertyName("subscribers_url")] string SubscribersUrl,
        [property: JsonPropertyName("subscription_url")] string SubscriptionUrl,
        [property: JsonPropertyName("commits_url")] string CommitsUrl,
        [property: JsonPropertyName("git_commits_url")] string GitCommitsUrl,
        [property: JsonPropertyName("comments_url")] string CommentsUrl,
        [property: JsonPropertyName("issue_comment_url")] string IssueCommentUrl,
        [property: JsonPropertyName("contents_url")] string ContentsUrl,
        [property: JsonPropertyName("compare_url")] string CompareUrl,
        [property: JsonPropertyName("merges_url")] string MergesUrl,
        [property: JsonPropertyName("archive_url")] string ArchiveUrl,
        [property: JsonPropertyName("downloads_url")] string DownloadsUrl,
        [property: JsonPropertyName("issues_url")] string IssuesUrl,
        [property: JsonPropertyName("pulls_url")] string PullsUrl,
        [property: JsonPropertyName("milestones_url")] string MilestonesUrl,
        [property: JsonPropertyName("notifications_url")] string NotificationsUrl,
        [property: JsonPropertyName("labels_url")] string LabelsUrl,
        [property: JsonPropertyName("releases_url")] string ReleasesUrl,
        [property: JsonPropertyName("deployments_url")] string DeploymentsUrl
    );

    public record GHA(
        [property: JsonPropertyName("total_count")] int? TotalCount,
        [property: JsonPropertyName("workflow_runs")] IReadOnlyList<WorkflowRun> WorkflowRuns
    );

    public record TriggeringActor(
        [property: JsonPropertyName("login")] string Login,
        [property: JsonPropertyName("id")] int? Id,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("avatar_url")] string AvatarUrl,
        [property: JsonPropertyName("gravatar_id")] string GravatarId,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("followers_url")] string FollowersUrl,
        [property: JsonPropertyName("following_url")] string FollowingUrl,
        [property: JsonPropertyName("gists_url")] string GistsUrl,
        [property: JsonPropertyName("starred_url")] string StarredUrl,
        [property: JsonPropertyName("subscriptions_url")] string SubscriptionsUrl,
        [property: JsonPropertyName("organizations_url")] string OrganizationsUrl,
        [property: JsonPropertyName("repos_url")] string ReposUrl,
        [property: JsonPropertyName("events_url")] string EventsUrl,
        [property: JsonPropertyName("received_events_url")] string ReceivedEventsUrl,
        [property: JsonPropertyName("type")] string Type,
        [property: JsonPropertyName("user_view_type")] string UserViewType,
        [property: JsonPropertyName("site_admin")] bool? SiteAdmin
    );

    public record WorkflowRun(
        [property: JsonPropertyName("id")] object Id,
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("node_id")] string NodeId,
        [property: JsonPropertyName("head_branch")] string HeadBranch,
        [property: JsonPropertyName("head_sha")] string HeadSha,
        [property: JsonPropertyName("path")] string Path,
        [property: JsonPropertyName("display_title")] string DisplayTitle,
        [property: JsonPropertyName("run_number")] int? RunNumber,
        [property: JsonPropertyName("event")] string Event,
        [property: JsonPropertyName("status")] string Status,
        [property: JsonPropertyName("conclusion")] string Conclusion,
        [property: JsonPropertyName("workflow_id")] int? WorkflowId,
        [property: JsonPropertyName("check_suite_id")] object CheckSuiteId,
        [property: JsonPropertyName("check_suite_node_id")] string CheckSuiteNodeId,
        [property: JsonPropertyName("url")] string Url,
        [property: JsonPropertyName("html_url")] string HtmlUrl,
        [property: JsonPropertyName("pull_requests")] IReadOnlyList<object> PullRequests,
        [property: JsonPropertyName("created_at")] DateTime? CreatedAt,
        [property: JsonPropertyName("updated_at")] DateTime? UpdatedAt,
        [property: JsonPropertyName("actor")] Actor Actor,
        [property: JsonPropertyName("run_attempt")] int? RunAttempt,
        [property: JsonPropertyName("referenced_workflows")] IReadOnlyList<object> ReferencedWorkflows,
        [property: JsonPropertyName("run_started_at")] DateTime? RunStartedAt,
        [property: JsonPropertyName("triggering_actor")] TriggeringActor TriggeringActor,
        [property: JsonPropertyName("jobs_url")] string JobsUrl,
        [property: JsonPropertyName("logs_url")] string LogsUrl,
        [property: JsonPropertyName("check_suite_url")] string CheckSuiteUrl,
        [property: JsonPropertyName("artifacts_url")] string ArtifactsUrl,
        [property: JsonPropertyName("cancel_url")] string CancelUrl,
        [property: JsonPropertyName("rerun_url")] string RerunUrl,
        [property: JsonPropertyName("previous_attempt_url")] object PreviousAttemptUrl,
        [property: JsonPropertyName("workflow_url")] string WorkflowUrl,
        [property: JsonPropertyName("head_commit")] HeadCommit HeadCommit,
        [property: JsonPropertyName("repository")] Repository Repository,
        [property: JsonPropertyName("head_repository")] HeadRepository HeadRepository
    );

