//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Text;

namespace SnapX.Core.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SnapX.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        public static Stream TaskCompletedSound
        {
            get
            {
                return GetSoundStream("TaskCompletedSound");
            }
        }
        public static Stream ActionCompletedSound
        {
            get
            {
                return GetSoundStream("ActionCompletedSound");

            }
        }
        public static Stream CaptureSound
        {
            get
            {
                return GetSoundStream("CaptureSound");
            }
        }
        public static Stream ErrorSound
        {
            get
            {
                return GetSoundStream("ErrorSound");
            }
        }

        private static Stream GetSoundStream(string soundName)
        {
            var assembly = Assembly.GetExecutingAssembly();
            var name = assembly.GetName().Name;
            return assembly.GetManifestResourceStream($"{name}.Resources.{soundName}.flac");
        }
    }
}
